### ISSUE TITLE
Add switch for led dreamview T1,T2

### ISSUE THREAD

**Issue by karnas99** [wez/govee-lan-hass#15]
I would like to kindly ask if is it possible to extend functionality for tv led strips dreamview T1,T2. Currently it is possible only to turn on and turn off. However it would be very handy to be able changing modes in HA. Especially toogling between color/movie mode.
Thanks
Jan

**Comment by wez** [comment]
Neither the HTTP nor the LAN API provide a way to work with modes.  It is technically possible to sniff the BLE traffic and control these via bluetooth, but you will need:

1. A bluetooth traffic sniffer and to capture the packets when you activate specific modes/settings using the govee home app
2. your HASS needs to have bluetooth and perhaps also have an esphome bluetooth proxy close enough to the device in order to control it.

**Comment by karnas99** [comment]
Thanks for your feedback, that´s something I am not currently capable of.

**Comment by Daneish** [comment]
The BLE traffic for the DreamView T1 (H6199) has been documented in [egold555/Govee-Reverse-Engineering](https://github.com/egold555/Govee-Reverse-Engineering/blob/master/Products/H6199.md).

Wez, thank you for all of your work on this project, it’s great! My T1 is currently broken (cat chomped through the cord), but I can fix it up and test if you were interested in implementing the BLE controls for the T1.

**Comment by wez** [comment]
I have no plans to work on this here in this integration, but I do want to note that my new [Govee2MQTT AddOn](https://github.com/wez/govee2mqtt) supports more devices, modes and scenes, so you may wish to consider moving to that.
