### ISSUE TITLE
Restriction regarding Home Assistant being on the same network...

### ISSUE THREAD

**Issue by ajtatum** [wez/govee-lan-hass#29]
I have my IoT stuff running on a VLAN, thusly a different subnet. There aren't any issues with Govee now, but from my understanding this integration wouldn't wok for me, is that correct?

**Comment by wez** [comment]
Govee's LAN protocol requires multicast UDP to be functional in order to discover the device addresses and their types.
If you somehow know that information already, it is technically possible, but there is no code to support it in this integration--someone would need to write it, *sending* commands via the LAN protocol to a different subnet, provided that it is routable.

Receiving information is another story: the devices return data by sending UDP packets to port 4003 of the originating address rather than by responding to the originating packet address and port.  If your network doesn't allow your IoT VLAN to send back to your HA address then the situation would be that you could potentially control the devices but not be able to get a response from them to see what their current state is.

It will likely be challenging to configure stateful firewall rules to match and allow "established" connections, as there are no connections with UDP, and these responses are really a separate unidirectional send rather than a reply.

These are limitations of Govee's LAN protocol architecture.

This integration will use the HTTP API to control your devices via the cloud if it cannot discover the LAN API information for a given device, so you should still be able to control your devices, just not via the LAN, if you decide to segregate them from your LAN.

I would suggest considering using a different technique to isolate govee's devices; perhaps MAC address based firewall rules that restrict LAN access to just UDP port 4003 on your hass node + internet access?

**Comment by ndom91** [comment]
FYI - if you're using opnsense for your firewall, there's a `udpbroadcastrelay` plugin available for just this type of use-case.

Check out: https://forum.opnsense.org/index.php?topic=15721.0

**Comment by xXMrJackXx** [comment]
I have a Unifi Network with 2 separate VLANS. My Home Assistant runs as a docker container with network_mode host in my trusted network, the Govee devices in my IOT network.
I have a firewall rule to allow communication from IOT to Home Assistant and activated Multicast DNS and IGMP Snooping for both networks.
I still cannot control the devices via LAN and my rate limit has already been exceeded.

Any ideas how to solve my problem?

**Comment by wez** [comment]
ask Govee support for guidance?

**Comment by xXMrJackXx** [comment]
The answer from Govee support was: "Lan API won't work across different VLans since the PC [hence Home Assistant] cannot communicate with the strip light in this case"
Well ...

**Comment by ndom91** [comment]
Yes they are technically correct, without any additional systems communicating across vlans/subnets here won't work. 

You will need to mirror udp broadcasts across the subnets, like with the opnsense plugin I mentioned above.

**Comment by gregg098** [comment]
Has anyone been successful in using UDP Broadcast Relay in OPNsense? I've been trying without any luck. I have a Home Assistant and Govee devices on different VLANS.  Home Assistant has full access to the IoT VLAN. Govee devices have access to Home Assistant ports 4001, 4002, and 4003 (TCP/UDP).  UDP Broadcast Relay was setup was for port 4003 with a broadcast address of 239.255.255.250 per the API documentation. I've also tried 1.1.1.1 and 1.1.1.2 in the source address without any luck. 

And yes, I did verify that my Govee devices have LAN control enabled.

**Comment by gregg098** [comment]
> Has anyone been successful in using UDP Broadcast Relay in OPNsense? I've been trying without any luck. I have a Home Assistant and Govee devices on different VLANS. Home Assistant has full access to the IoT VLAN. Govee devices have access to Home Assistant ports 4001, 4002, and 4003 (TCP/UDP). UDP Broadcast Relay was setup was for port 4003 with a broadcast address of 239.255.255.250 per the API documentation. I've also tried 1.1.1.1 and 1.1.1.2 in the source address without any luck.
> 
> And yes, I did verify that my Govee devices have LAN control enabled.

I actually got it to work after I posted. I think I just needed to cycle the broadcast relay instance and reload the integration.

Just to recap. Home Assistant already has full access to the IoT VLAN.
Made a firewall alias with all Govee Devices. Made another with ports 4001, 4002, 4003.
Made a firewall rule to allow Source: Govee Devices Destination: HA Ports: Govee Ports

UDP Broadcast Relay instance looks like this:
![image](https://github.com/wez/govee-lan-hass/assets/24879443/1d2c573d-a5a9-48b8-b0a5-e03d81c0c43e)

Then make sure you restart Home Assistant or at least reload the integration. 
Have not done much testing yet.

**Comment by SuperSandro2000** [comment]
For OpenWrt there is no GUI and I am just starting ``udp-broadcast-relay-redux`` in ``/etc/rc.local``.

```bash
# bridge Govee LAN API UDP ports
udp-broadcast-relay-redux --id 1 --port 4001 --dev br-lan --dev phy1-ap1 --multicast 239.255.255.250 &
udp-broadcast-relay-redux --id 1 --port 4002 --dev br-lan --dev phy1-ap1 --multicast 239.255.255.250 &
udp-broadcast-relay-redux --id 1 --port 4003 --dev br-lan --dev phy1-ap1 --multicast 239.255.255.250 &
```

**Comment by SuperSandro2000** [comment]
Update: I am not sure if the last update is responsible for this but now I am required to enter an API key even if the LED chain has no access to the internet and I enabled the LAN API before.

Also if I add udp port 1900 to udp-broadcast-relay-redux the govee desktop applications shows that LAN works as expected, which I think it didn't before but it somehow worked over wifi.

Can't really recommend this producer the longer I use it....

**Comment by wez** [comment]
I have no plans to improve things around this here in this integration, but I do want to note that my new [Govee2MQTT AddOn](https://github.com/wez/govee2mqtt) gives you a bit more control and allows you to list out individual IPs for networks where multicast and broadcast UDP cannot be relied upon for discovery.  So you may wish to consider moving to that.

**Comment by danielebra** [comment]
After spending quite a bit of time down the rabbit hole of trying to get Govee devices to be discoverable across IoT VLANs, I can highly recommend using @wez 's Govee2MQTT addon with static IPs allocated to the Govee devices and listing them out in the `Additional IPs and broadcast addresses to scan` section of the configuration.
