### ISSUE TITLE
Can HTTP control be disabled, and only LAN control be used?

### ISSUE THREAD

**Issue by borisb13** [wez/govee-lan-hass#35]
I have an H6073 lamp, and it work perfectly fine with this integration. However, a lot of the time there's a delay of several seconds before  it turns on/off. Sometimes that delay is almost 10 seconds. 

So, just for testing purposes, I changed the API key in this integration (after if was already successfully set up) to something invalid, hoping that would break HTTP connectivity, but not LAN control. **And it worked**! LAN control was still working perfectly, and there was no longer any delay at all. I then changed the API key back to the correct one, and the delay immediately came back (only a second or two, but definitely noticeable). I repeated this process, and confirmed that the delay is definitely gone when the wrong API key was entered.

So, I kept the wrong API key, hoping it could just stay that way forever. Unfortunately, after a few days running that way, the lamp dropped of the network, and I had to reload this integration from scratch to get it working. I changed it to the wrong API key yet again, but I'm guessing that I'll have this issue again in a few days. 

And that brings me to my request -- is there a way to add a configuration variable that will completely disable HTTP control inf favor of only using LAN control? I understand that it could potentially cause some issues, but it would be great if it at least were an option

**Comment by wez** [comment]
If you delete the configuration, then re-add it, but omit the API key when you add it back in, it should use only LAN control.
This is (not very clearly) discussed in https://github.com/wez/govee-lan-hass#installation

The consequence of not using the HTTP API to bootstrap is that the device names are not (because they cannot be) pre-set or updated when you change their names in the govee app, and the entity ids will be different as well.

**Comment by borisb13** [comment]
I just tried doing that, but if I don't enter the API key, it doesn't add any devices at all. The integration itself shows up, but it says "no devices or entities", and I don't see any way to add one manually

**Comment by 51av0sh** [comment]
Are you segregating your network with vlans? Is your home assistant and the Govee devices on the same network?

**Comment by 51av0sh** [comment]
Gotcha. I don't believe that would matter. I have devices in different VLANs that can ping from my main network but discovery doesn't work properly across them. Discovery is a very unique beast that I've not been able to get working reliably no matter what I try (I've also setup bridges)

**Comment by borisb13** [comment]
Is there anything I can do to manually enter the IP of the Govee? It's got
a static DHCP assignment, so the IP will never change

**Comment by 51av0sh** [comment]
Good question. I'm not sure. Hopefully someone else chimes in.

**Comment by mcgarley** [comment]
I have VLANs so can't use this integration. It would be great just to manually specify IP addresses of the devices.

**Comment by the01** [comment]
@borisb13 @mcgarley I don't think it is possible to set the ip via a config manually at the moment. I ended up modifying the installed source code of the component directly. In `light.py` I extended the `async_setup_entry()` function with a call to `controller._lan_poller_process_broadcast()` with the data that would have been received from the lan scan.

It is messy, since you have to manually add this for every device you want to have and will need to be redone after every update to the integration, but it works.
UDP traffic between HA and the Govee devices is of course still required (both ways), but at least the multicast issues can be bypassed like this.
It has been running like this only for a short while, so I don't have any experience on long term stability yet.

**Comment by wez** [comment]
I have no plans to fix that here in this integration, but I do want to note my new [Govee2MQTT AddOn](https://github.com/wez/govee2mqtt) will let you list out devices by IP, so you may want to try switching to that.
