### ISSUE TITLE
Add Ability to Control Govee Scenes with New Development Platform

### ISSUE THREAD

**Issue by superpunkduck** [wez/govee-lan-hass#50]
Recently Govee Released the new Development Platform...
https://app-h5.govee.com/share/community?client=0&postId=165266&t=1701725633893

Is there any way the integration could be update to allow HA to control Govee Scenes, Music Modes, and DIY rather than Just Single Colors and Power?

**Comment by mattgphoto** [comment]
Looked for the issues on this to find out if this had been requested yet or if it was just something I was missing, this would be invaluable for a QoL Feature Request.

**Comment by mattgphoto** [comment]
@superpunkduck I think we have our answer here actually... https://github.com/wez/govee-lan-hass/issues/42#issuecomment-1783608157 Unless Govee exposes this information, I think we're out of luck.

**Comment by wez** [comment]
FWIW, I've been doing some reverse engineering the past couple of days and have found a way to send scene controls via undocumented parts of the LAN protocol (https://github.com/egold555/Govee-Reverse-Engineering/issues/11))

My strategy for taking advantage of this new knowledge is *not* to update govee-lan-hass directly, but rather to build a home assistant addon instead; that approach means that I can move much more rapidly with development, using Rust as well, and also tackle some issues that folks have with routing of LAN packets across subnets.

The addon approach has worked out really well for me with my [Power View](https://github.com/wez/pview/) integration, so I'm excited to apply it here to my govee lights as well.

**Comment by Tom-Sumner** [comment]
@wez 
Just reading your comment and im not clear wether you plan on integrating scenes, diys and the other new things in your new version. sorry if i misunderstood

**Comment by wez** [comment]
Yes, the new addon will support scenes

**Comment by Tom-Sumner** [comment]
amazing cant wait to try this out. loving it so far

**Comment by Worren** [comment]
> amazing cant wait to try this out. loving it so far

Same for me :-)

**Comment by wez** [comment]
My work so far is up at:
* https://github.com/wez/govee2mqtt#govee-to-mqtt-bridge-for-home-assistant

To run it, you'll need docker.

**Comment by superpunkduck** [comment]
> My work so far is up at:
> 
> * https://github.com/wez/govee2mqtt#govee-to-mqtt-bridge-for-home-assistant
> 
> To run it, you'll need docker.

So this wont work for someone running a straight HASS install without it being inside docker?

Will it ever?

**Comment by wez** [comment]
I'll add a hass addon in the near future, but otherwise: no, I have no plans to make this work as a regular hass integration.  The reasons are:

* I find it extremely frustrating to split the work across two separate python-based projects (this one, and the underlying python library which is just the govee API), which is a requirement for hass integrations. It makes development very slow going, and makes it harder to develop both components.
* I do not enjoy working in python, which means I don't really want to look at either project very often.
* The UDP discovery stuff required for Govee's LAN API is a PITA and I found it much easier to deal with it in the context of a a long lived process
* It is possible to iterate on govee2mqtt without bouncing my whole home automation system

That said, you don't have to use docker to run `govee2mqtt`, you can just compile and run the executable outside of docker.

**Comment by mattgphoto** [comment]
Appreciate the effort @wez. I don't have machines to spin up docker on anymore, and don't know the first thing about compiling something in windows or about setting mqtt. But that is not your fault, and I hope this works great for you!

**Comment by Tom-Sumner** [comment]
> I'll add a hass addon in the near future, but otherwise: no, I have no plans to make this work as a regular hass integration. The reasons are:
> 
> * I find it extremely frustrating to split the work across two separate python-based projects (this one, and the underlying python library which is just the govee API), which is a requirement for hass integrations. It makes development very slow going, and makes it harder to develop both components.
> * I do not enjoy working in python, which means I don't really want to look at either project very often.
> * The UDP discovery stuff required for Govee's LAN API is a PITA and I found it much easier to deal with it in the context of a a long lived process
> * It is possible to iterate on govee2mqtt without bouncing my whole home automation system
> 
> That said, you don't have to use docker to run `govee2mqtt`, you can just compile and run the executable outside of docker.

I quite enjoy working in Python. Could I help you out anyway in the hass addon development?

**Comment by superpunkduck** [comment]
> I'll add a hass addon in the near future, but otherwise: no, I have no plans to make this work as a regular hass integration. The reasons are:
> 
> * I find it extremely frustrating to split the work across two separate python-based projects (this one, and the underlying python library which is just the govee API), which is a requirement for hass integrations. It makes development very slow going, and makes it harder to develop both components.
> * I do not enjoy working in python, which means I don't really want to look at either project very often.
> * The UDP discovery stuff required for Govee's LAN API is a PITA and I found it much easier to deal with it in the context of a a long lived process
> * It is possible to iterate on govee2mqtt without bouncing my whole home automation system
> 
> That said, you don't have to use docker to run `govee2mqtt`, you can just compile and run the executable outside of docker.

...... Unfortunately that's all Greek to me... I typically am pretty good at following install instructions... but i look at this and get really confused...

That being said... i appreciate all your effort.

**Comment by wez** [comment]
@mattgphoto how are you running home assistant at the moment?

**Comment by Tom-Sumner** [comment]
> @mattgphoto how are you running home assistant at the moment?

Im just running it on my RPI 3B as the OS itself. is there any way I can use this yet?

**Comment by wez** [comment]
@Tom-Sumner which of these installation methods did you use? https://www.home-assistant.io/installation/#advanced-installation-methods

**Comment by Tom-Sumner** [comment]
> @mattgphoto how are you running home assistant at the moment?

I used the OS flasher windows app. to flash it to the boot sd

**Comment by mattgphoto** [comment]
> @mattgphoto how are you running home assistant at the moment?

I have HAOS installed in a VM with HACS.

**Comment by sdaltons1** [comment]
@wez 

Hey Wez, thanks for doing this.

I see the documentation mentions support for the platform api. Does that mean this integration will be able to pull in all govee devices, including appliances, rather than just those with lan api support?

**Comment by wez** [comment]
@sdaltons1 yes, all devices should be visible to it, however, since I only have lights to test against, right now it will simply represent them all as lights, so you may not be able to much more than just turn the power on or off.

**Comment by wez** [comment]
OK, for folks that are running HAOS or Supervised Home Assistant, you should now be able to install govee2mqtt as an addon.
https://www.home-assistant.io/addons/ has more information about add-ons

The steps are shown below; it's a bit of an adventure in clicking all over the place because of how HASS lays these things out, but it isn't especially difficult.

Steps:

1. Go to the AddOns page: https://my.home-assistant.io/redirect/supervisor
2. Click on the "Add-on store" button (look to the bottom right)
3. Look for the Mosquitto Broker
   * "Install" it
   * "Start" it
4. Now go to "Settings" "Devices & Services" and enable the MQTT integration.
5. Go back to the AddOns Store
6. Look for the 3 vertically stacked dots in the top right corner:

![image](https://github.com/wez/govee-lan-hass/assets/117777/c425615b-d7be-4ff2-a0d9-c8b7cfb8b63e)

7. Click on "Repositories"
8. Enter `https://github.com/wez/govee2mqtt` and click "Add"
9. You should see:

![image](https://github.com/wez/govee-lan-hass/assets/117777/a2603e2d-dec1-4711-8d94-c957bf4a7a01)

10. Click "close"
11. To make it show up in the "Store" area you need to ensure that "Advanced Mode" is turned on for your profile. There is a little link at the bottom of the screen you can click on, but otherwise you can click on your profile icon in the bottom left corner of the screen. Enable advanced mode:

![image](https://github.com/wez/govee-lan-hass/assets/117777/444c399d-0a91-41bf-804e-efcbabe17635)

12. Go back to the AddOns Store
13. You should now see:

![image](https://github.com/wez/govee-lan-hass/assets/117777/4e70f5e4-d54e-4e95-94db-b1d4a562eab1)

14. Click on it
15. Click "install"
16. At the top of the screen is a "Configuration" tab, click it

![image](https://github.com/wez/govee-lan-hass/assets/117777/fd2953b5-a576-4ab4-a903-0330a749ae97)

17. Check the "Show unused optional configuration options" option
18. Fill out at least the first three options; the govee email, password and api key
19. You don't need to fill out the mqtt options because you are using the integrated Mosquitto Addon; the appropriate values are automatically passed through
20. Click "Save" (bottom right)
21. Click on the "Info" tab (top of screen)
22. Now you can click "Start" to launch it

**Comment by wez** [comment]
Assuming it's all working, after a couple of seconds, you'll see your devices show up under the MQTT integration in Devices and Services, and any other dashboards that automatically populate.

**Comment by Worren** [comment]
Just a note - you have to deactivate the govee-lan-hass integration in Home Assitant to try the new govee2mqtt integration.

**Comment by superpunkduck** [comment]
It's working great for me so far.... Any idea on how to get it to react to music for devices with built in mics....

Here's an example of the music scenes I'm looking for in the govee app
![Screenshot_20240104-164840](https://github.com/wez/govee-lan-hass/assets/50434137/53040409-b027-4dfe-b209-1cf27aeaac6b)

**Comment by jiwe69** [comment]
I got it working very easily with @wez instructions, thank you so much!!

**Comment by wez** [comment]
Closing this as [Resolved by switching to Govee2MQTT](https://github.com/wez/govee2mqtt)
