### ISSUE TITLE
Make entity unavailable when not connected

### ISSUE THREAD

**Issue by AdmiralRaccoon** [wez/govee-lan-hass#9]
Hello,
When the Govee device isn´t connectedl to wifi, due to planned / unplanned events (eg. plug pulled), the entitiy in Home Assistant can still be turned on/off.
Is it possible that the device changes to "unavailable" after a certain amount of time? (eg with in internal ping), and goes to "off" when it´s reconnected?

Thank you,
Philipp

**Comment by wez** [comment]
Take a look at the notes in the readme for a bit more info on the polling strategy:
https://github.com/wez/govee-lan-hass#notes

The devices should get polled once a minute via the LAN API. I've definitely seen my devices show as unavailable in a couple of problem scenarios.

If you add this to your `configuration.yaml`, you'll get verbose logging that might reveal more about what's happening:

```yaml
logger:
  logs:
    custom_components.govee_lan: debug
    govee_led_wez: debug
```

**Comment by wez** [comment]
I've pushed a commit that will mark a light as unavailable after two consecutive poll timeouts.  Why not immediately on the first one?  The govee devices aren't great at responding to LAN control status requests, so it can legitimately be available but not good at reporting, and falsely show as unavailable and prevent you from attempting to control the device when it would otherwise work :-/

**Comment by AdmiralRaccoon** [comment]
Thank you, works fine so far!

<img width="489" alt="image" src="https://user-images.githubusercontent.com/41727850/212168199-c0c330a7-6343-4989-8deb-3f3650107da3.png">
